### ISSUE TITLE
Hi, guys! 

### ISSUE THREAD

**Issue by Viktor-Skopin** [Vaomi/Puzzle#2]
![alt text](https://avatars.mds.yandex.net/get-lpc/1527204/f6934e95-026d-44cb-9b11-4111bfd6953a/orig)

**Comment by Xenirum-Core** [comment]
Да-да

**Comment by Viktor-Skopin** [comment]
> Да-да

Одобряю

**Comment by Xenirum-Core** [comment]
Бибобряю

**Comment by Xenirum-Core** [comment]
Нужно дать рекомендации на развитие проекта, есть идеи?

**Comment by Viktor-Skopin** [comment]
Вот моя рекомендация 
![alt text](https://lh3.googleusercontent.com/proxy/YvypYzKerR5E-AwjW_6gVHZKJ5AevMuNMwDViEOg4TSpWbru3P-TT_Ep5kcsJUSt7Adv8iL7MmSIpGMaf8JJ3x1jev2VI30r-WicqGPaM1QTzmzBOUphn5O_BDxp1Ln82TI)

**Comment by Xenirum-Core** [comment]
> Вот моя рекомендация
> ![alt text](https://camo.githubusercontent.com/9bfb974bd05d33892d82392f6a184b37885a762cd534f198b7c02ca160d3d27b/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f70726f78792f59767970597a4b65725235452d41776a575f366756485a4b4a354165764d754e4d77445669454f67345453705762727533502d54545f4570356b63734a5553743741647638694c374d6d534970474d6166384a4a3378316a65763256493330722d576963714750614d3151547a6d7a424f5570686e354f5f42447870314c6e38325449)

Полностью поддерживаю

**Comment by Xenirum-Core** [comment]
![](https://memepedia.ru/wp-content/uploads/2018/02/mafioznik-mem.jpg)
Руки вверх!

**Comment by Viktor-Skopin** [comment]
![](https://static.barahla.net/images/content/2020/07/14/d/a/k57ES.jpg)

**Comment by Xenirum-Core** [comment]
Поддерживаете ли вы гомосексулистов?

- [x] Да, поддерживаю

- [ ] Нет, но поддерживаю

**Comment by Xenirum-Core** [comment]
Кем является владелец репозитория?
Ответы жду в сабтреде

**Comment by Viktor-Skopin** [comment]
Так подожжжи

**Comment by Xenirum-Core** [comment]
Пожалуй я оставлю свой CUMment

**Comment by Xenirum-Core** [comment]
Эй, остались тут ещё адекватные CUMментаторы?

**Comment by Viktor-Skopin** [comment]
![Uploading 13.jpg…]()

**Comment by Viktor-Skopin** [comment]
![21](https://user-images.githubusercontent.com/67225658/107652576-c9679a80-6c91-11eb-8d7d-258a71a3e209.jpg)

**Comment by Viktor-Skopin** [comment]
![53621-gorod_vektor_neon_zdaniya](https://user-images.githubusercontent.com/67225658/107652738-f2882b00-6c91-11eb-8934-6b8b8f37fb1c.jpg)

**Comment by Xenirum-Core** [comment]
> ![53621-gorod_vektor_neon_zdaniya](https://user-images.githubusercontent.com/67225658/107652738-f2882b00-6c91-11eb-8934-6b8b8f37fb1c.jpg)
> 

Шо это

**Comment by Viktor-Skopin** [comment]
:ok_hand:

**Comment by Xenirum-Core** [comment]
Подловил значит. Вот чертила

**Comment by Viktor-Skopin** [comment]
👁👅👁

**Comment by Viktor-Skopin** [comment]
👉🏼👌🏼

**Comment by Viktor-Skopin** [comment]
👮🏿

**Comment by Xenirum-Core** [comment]
Быть такого не может.
